spring:
  datasource:
    url: jdbc:postgresql://159.69.215.108:5432/magiDB
    username: magiuser
    password: 2552
    driver-class-name: org.postgresql.Driver
  jackson:
    time-zone: Europe/Madrid

  jpa:
    hibernate:
      ddl-auto: update            
    show-sql: true                
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true          
        default_schema: public

logging:
  level:
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: DEBUG

magi:
  centre-id: 366781135       
  ausencias:
    gracia-min: 5
    plantilla: PL1     
